name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm format --check --no-write
          pnpm lint
          pnpm test

      - working-directory: example
        run: |
          pnpm build

      - uses: actions/upload-pages-artifact@v5
        with:
          path: example/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
